# Generated by Django 4.1.2 on 2022-11-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=55)),
                ('bithdate', models.DateField()),
                ('phone', models.IntegerField()),
                ('standard', models.IntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('local_address', models.TextField(max_length=200)),
                ('permanent_address', models.TextField(max_length=200)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=55)),
                ('bithdate', models.DateField()),
                ('phone', models.IntegerField()),
                ('local_address', models.TextField(max_length=200)),
                ('permanent_address', models.TextField(max_length=200)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
