# Generated by Django 4.1.3 on 2022-11-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_schooluser_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolUser',
        ),
    ]
