# Generated by Django 4.1.3 on 2022-11-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_bithdate_schooluser_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooluser',
            old_name='users_code',
            new_name='user_type',
        ),
    ]
