# Generated by Django 4.1.3 on 2022-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_schooluser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], default='Unknown', max_length=10),
        ),
    ]
