# Generated by Django 4.1.3 on 2022-11-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_schooluser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='local_address',
            field=models.TextField(blank=True, default='Pakistan', max_length=200, null=True),
        ),
    ]
