# Generated by Django 4.1.3 on 2022-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_schooluser_local_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='local_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
