# Generated by Django 4.1.3 on 2022-11-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_schooluser_local_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='local_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='permanent_address',
            field=models.TextField(default='Karachi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
