# Generated by Django 4.1.3 on 2022-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_schooluser_local_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='permanent_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
