# Generated by Django 4.1.3 on 2022-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_schooluser_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='local_address',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='permanent_address',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
