# Generated by Django 4.1.3 on 2022-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_schooluser_local_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
