# Generated by Django 4.1.3 on 2022-11-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_schooluser_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='local_address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='permanent_address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
