# Generated by Django 4.1.3 on 2022-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_schooluser_local_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=10),
        ),
    ]
