# Generated by Django 4.1.3 on 2022-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_schooluser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
