# Generated by Django 4.1.3 on 2022-11-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_schooluser_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='terms_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
