# Generated by Django 4.1.3 on 2022-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_schooluser_terms_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_type',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student')], max_length=50),
        ),
    ]
