# Generated by Django 4.1.3 on 2022-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_schooluser_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='email',
            field=models.EmailField(default='unknown@gmail.com', max_length=254, unique=True),
        ),
    ]
