# Generated by Django 4.1.3 on 2022-12-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_schooluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
