# Generated by Django 4.1.3 on 2022-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_schooluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_icon',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
