# Generated by Django 4.1.2 on 2022-12-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_schooluser_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile-icon'),
        ),
    ]
