# Generated by Django 4.1.2 on 2023-01-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_useraddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_icon',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/profile-icon'),
        ),
    ]
