# Generated by Django 4.1.2 on 2023-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_schooluser_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user_icon',
            field=models.ImageField(blank=True, default='images/no-profile-icon/default.png', upload_to='images/profile-icon'),
        ),
    ]
