# Generated by Django 4.1.2 on 2023-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_schooluser_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='standard',
            field=models.IntegerField(blank=True, default=786),
        ),
    ]
