# Generated by Django 4.1.2 on 2023-01-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_schooluser_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='standard',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
