# Generated by Django 4.1.2 on 2022-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_courses_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_enroll_name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_teacher_name',
            new_name='teacher_name',
        ),
    ]
