# Generated by Django 4.1.2 on 2022-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_course_enroll_name_courses_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student_address',
            field=models.TextField(default='Not Found'),
        ),
        migrations.AddField(
            model_name='courses',
            name='student_city',
            field=models.CharField(default='not found', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='student_email',
            field=models.EmailField(default='ddd', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='student_state',
            field=models.CharField(default='ghj', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='student_zip',
            field=models.IntegerField(default=54325),
            preserve_default=False,
        ),
    ]
