# Generated by Django 4.1.2 on 2022-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_courses_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student_address',
            field=models.CharField(max_length=60),
        ),
    ]
