# Generated by Django 4.1.2 on 2022-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_courses_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='standard',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
