# Generated by Django 4.1.2 on 2022-12-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_courses_course_name_alter_courses_course_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='standard',
            new_name='student_standard',
        ),
    ]
