# Generated by Django 4.1.2 on 2022-12-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_courses_id_courses_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='price',
            new_name='course_price',
        ),
    ]
