# Generated by Django 4.1.2 on 2022-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_courses_course_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('teacher_name', models.CharField(blank=True, max_length=120)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=55)),
                ('student_address', models.CharField(max_length=60)),
                ('student_city', models.CharField(max_length=30)),
                ('student_state', models.CharField(max_length=30)),
                ('student_zip', models.IntegerField()),
                ('student_standard', models.IntegerField(blank=True)),
                ('enroll_time', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.CharField(blank=True, max_length=10)),
                ('course_price', models.IntegerField(blank=True)),
                ('course_confirmation', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
