# Generated by Django 4.1.2 on 2022-12-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_studentpurchases_delete_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentPurchases',
            new_name='CoursePurchases',
        ),
    ]
