# Generated by Django 4.1.2 on 2022-12-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_rename_studentpurchases_coursepurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepurchases',
            name='course_confirmation',
        ),
    ]
