# Generated by Django 4.1.2 on 2022-12-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_coursepurchases_course_confirmation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursepurchases',
            table='Student_Courses_Purchase',
        ),
    ]
