# Generated by Django 4.1.2 on 2022-12-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_coursepurchases_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursepurchases',
            table='student_courses_purchase',
        ),
    ]
