# Generated by Django 4.1.2 on 2023-01-02 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_courses_course_type'),
        ('students', '0019_alter_coursepurchases_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepurchases',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='course_price',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_address',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_city',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_standard',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='student_state',
        ),
        migrations.RemoveField(
            model_name='coursepurchases',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='coursepurchases',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teachers.courses'),
            preserve_default=False,
        ),
    ]
