# Generated by Django 4.1.2 on 2023-01-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_courses_user'),
        ('students', '0021_rename_user_coursepurchases_course_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepurchases',
            name='course_info',
        ),
        migrations.CreateModel(
            name='CourseAddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.courses')),
            ],
        ),
        migrations.AddField(
            model_name='coursepurchases',
            name='course_checkout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.courseaddtocart'),
            preserve_default=False,
        ),
    ]
