# Generated by Django 4.1.2 on 2023-01-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_coursepurchases_course_info_courseaddtocart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseaddtocart',
            old_name='course_add',
            new_name='teacher_course',
        ),
        migrations.RenameField(
            model_name='coursepurchases',
            old_name='course_checkout',
            new_name='course_add_cart',
        ),
    ]
