# bitbucket-pipelines.yml

image: python:3.10.12

pipelines:
  default:
    - step:
        name: Run pushing test cases
        caches:
          - pip
        script:
          - pip install -r requirements
          - python manage.py test
