# bitbucket-pipelines.yml

image: python:3.7.12  # Preferred container python version

pipelines:
  default:
    - step:
        name: Run branch pushing test cases
        caches:
          - pip
        script:
          - pip install --upgrade pip # Update pip first, If necessary.
          - pip install -r requirements # requirements module file.
          - python manage migrate # Build database.
          - python manage.py runserver # Run server and catch error, If any.
          - python manage.py test # Run test cases.

