# Generated by Django 4.1.2 on 2022-12-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
