# Generated by Django 4.1.2 on 2022-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default='Dhaval', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
