# Generated by Django 4.1.2 on 2022-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher_name',
            field=models.CharField(default='me', max_length=120),
        ),
    ]
