# Generated by Django 4.1.2 on 2022-12-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0007_alter_courses_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
