# Generated by Django 4.1.2 on 2023-01-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_courses_teacher_name_courses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[('free', 'FREE'), ('paid', 'PAID')], max_length=10),
        ),
    ]
