# Generated by Django 4.1.2 on 2023-01-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0009_alter_courses_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'T'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
