# Generated by Django 4.1.2 on 2022-11-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=44)),
                ('established_year', models.IntegerField()),
                ('owner_name', models.CharField(max_length=25)),
                ('address', models.TextField(max_length=100)),
                ('rating', models.CharField(choices=[('A', 'Good Institute'), ('B', 'Average Institute'), ('C', 'Very Poor Institute')], max_length=5)),
            ],
        ),
    ]
