# Generated by Django 4.1.3 on 2022-11-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtonschool', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
