# MODELS ALL CHOICES DEFINED HERE....


# 1. MODEL - COURSES CHOICES..
TEACHER_COURSE_PRICE_FREE = 'free'
TEACHER_COURSE_PRICE_PAID = 'paid'

COURSE_TYPE_CHOICES = [(TEACHER_COURSE_PRICE_FREE, 'FREE'),
                       (TEACHER_COURSE_PRICE_PAID, 'PAID')]
