name: Django DRF with Apache Solr and PostgreSQL CI
'on':
  push:
    branches:
      - feat/github-workflow-setup
  pull_request:
    branches:
      - main
env:
  DJANGO_SETTINGS_MODULE: "school.test_settings"
jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:14'
        env:
          POSTGRES_DB: test_electo_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s
          --health-timeout 5s --health-retries 5
      solr:
        image: 'solr:8.9.0'
        ports:
          - '8983:8983'
        options: '--name ct-solr -e SOLR_HEAP=512m'
        env:
          SOLR_JAVA_MEM: '-Xms512m -Xmx512m'
    steps:
      - name: Print settings module
        env:
          MY_CUSTOM: ${{ vars.PROJECT_OWNER }}
        run: |
          echo "DJANGO_SETTINGS_MODULE is set to: ${{ vars.DJANGO_SETTINGS_MODULE }}"
          echo "Project owner is set to: ${{ vars.PROJECT_OWNER }}"
          echo "settings module: ${{ env.DJANGO_DHAVAL }}"


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Apache Solr
        run: |
          docker exec ct-solr solr create -c electo_core -d sample_techproducts_configs
          echo "Solr core 'electo_core' successfully created"    

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Set up the Django project
        env:
          DJANGO_SETTINGS_MODULE: "ok"
        run: |
          python -c "import os; print(os.environ.get('DJANGO_SETTINGS_MODULE'))"
          python manage.py migrate
          python -c "import os; print(os.environ.get('DJANGO_SETTINGS_MODULE'))"

      - name: Run tests
        run: |
          echo "settings test module: ${{ env.USER }}"
          python manage.py test
          pwd
          python -c "import os; print(os.environ.get('DJANGO_SETTINGS_MODULE'))"
