name: Django DRF with Apache Solr and PostgreSQL CI
'on':
  push:
    branches:
      - feat/github-workflow-setup
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:14'
        env:
          POSTGRES_DB: test_electo_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s
          --health-timeout 5s --health-retries 5
      solr:
        image: 'solr:8.9.0'
        ports:
          - '8983:8983'
        options: '--name test-solr -e SOLR_HEAP=512m'
        env:
          SOLR_JAVA_MEM: '-Xms512m -Xmx512m'
    steps:
      - name: Print settings module
        run: >
          echo "DJANGO_SETTINGS_MODULE is set to: ${{
          vars.DJANGO_SETTINGS_MODULE }}"

          echo "Project owner is set to: ${{ vars.PROJECT_OWNER }}"

          echo "Project City is set to: ${{ secrets.CITY }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up PostgreSQL
        run: >
          sudo apt-get install postgresql-client

          psql -h localhost -U postgres -d mydatabase -c "CREATE DATABASE
          electo_db;"

          psql -h localhost -U postgres -d mydatabase -c "CREATE USER django
          WITH PASSWORD 'password';"

          psql -h localhost -U postgres -d mydatabase -c "GRANT ALL PRIVILEGES
          ON DATABASE electo_db TO django;"
      - name: Create Solr core
        run: >
          docker exec -it test-solr solr create -c electo_core -d
          sample_techproducts_configs

          echo "Solr core 'electo_core' created"
      - name: Set up the Django project
        env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/test_electo_db'
          SOLR_URL: 'http://localhost:8983/solr/electo_core'
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
      - name: Run tests
        env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/test_electo_db'
          SOLR_URL: 'http://localhost:8983/solr/electo_core'
        run: |
          python manage.py test
